import { Order } from '@/types/orders';

export const orders: Order[] = [
  {
    id: '1',
    customer: 'Sophie Martin',
    restaurant: 'Restaurant Teranga',
    address: '12 Rue de la Paix, Plateau, Dakar',
    items: 3,
    distance: '1.2 km',
    earnings: 5500,
    time: '25 min',
    status: 'available',
    urgent: true,
    lat: 14.6696,
    lng: -17.4441,
    phone: '+221771234567',
  },
  {
    id: '2',
    customer: 'Thomas Dubois',
    restaurant: 'Chez Loutcha',
    address: '45 Avenue Blaise Diagne, Médina, Dakar',
    items: 2,
    distance: '2.1 km',
    earnings: 7806,
    time: '30 min',
    status: 'accepted',
    urgent: false,
    lat: 14.6718,
    lng: -17.4462,
    phone: '+221775678901',
  },
  {
    id: '3',
    customer: 'Marie Durand',
    restaurant: 'Le Djembe',
    address: '8 Boulevard du Centenaire, Plateau, Dakar',
    items: 1,
    distance: '0.8 km',
    earnings: 4400,
    time: '15 min',
    status: 'available',
    urgent: false,
    lat: 14.6729,
    lng: -17.4414,
    phone: '+221783456789',
  },
  {
    id: '4',
    customer: 'Jean Moreau',
    restaurant: 'Café de Rome',
    address: '23 Avenue Pompidou, Plateau, Dakar',
    items: 4,
    distance: '1.5 km',
    earnings: 6000,
    time: '20 min',
    status: 'picked_up',
    urgent: false,
    lat: 14.6708,
    lng: -17.4475,
    phone: '+221701234567',
  },
];

export const markers = orders.map((order) => ({
  lat: order.lat,
  lng: order.lng,
  name: order.restaurant,
  address: order.address,
}));
